//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galerie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Galerie()
        {
            this.Tip = "poza";
            this.Grups = new HashSet<Grup>();
        }
    
        public int Id_galerie { get; set; }
        public System.DateTime DataCreare { get; set; }
        public string Eveniment { get; set; }
        public string Locatie { get; set; }
        public string Adresa { get; set; }
        public string Tip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grup> Grups { get; set; }
    }
}
